config/routes.rb
Rails.application.routes.draw do
  resources :comments,:railsblogs,:news
  # resources :railsblogs
  # resources :news
  # get 'page/home'
  # get 'page/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/railsblog.rb
class Railsblog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :description)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/railsblogs_controller.rb
class RailsblogsController < ApplicationController
  before_action :set_railsblog, only: %i[ show edit update destroy ]

  # GET /railsblogs or /railsblogs.json
  def index
    @railsblogs = Railsblog.all
  end

  # GET /railsblogs/1 or /railsblogs/1.json
  def show
  end

  # GET /railsblogs/new
  def new
    @railsblog = Railsblog.new
  end

  # GET /railsblogs/1/edit
  def edit
  end

  # POST /railsblogs or /railsblogs.json
  def create
    @railsblog = Railsblog.new(railsblog_params)

    respond_to do |format|
      if @railsblog.save
        format.html { redirect_to railsblog_url(@railsblog), notice: "Railsblog was successfully created." }
        format.json { render :show, status: :created, location: @railsblog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @railsblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railsblogs/1 or /railsblogs/1.json
  def update
    respond_to do |format|
      if @railsblog.update(railsblog_params)
        format.html { redirect_to railsblog_url(@railsblog), notice: "Railsblog was successfully updated." }
        format.json { render :show, status: :ok, location: @railsblog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @railsblog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railsblogs/1 or /railsblogs/1.json
  def destroy
    @railsblog.destroy

    respond_to do |format|
      format.html { redirect_to railsblogs_url, notice: "Railsblog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railsblog
      @railsblog = Railsblog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def railsblog_params
      params.require(:railsblog).permit(:title, :upload, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/railsblogs_helper.rb
module RailsblogsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.number_field :post_id %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
   
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Title:</strong>
    <%= news.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= news.description %>
  </p>

</div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Show this news", @news %> |
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>News</h1>

<div id="news">
  <% @news.each do |news| %>
    <%= render news %>
    <p>
      <%= link_to "Show this news", news %>
    </p>
  <% end %>
</div>

<%= link_to "New news", new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @news %>

<div>
  <%= link_to "Edit this news", edit_news_path(@news) %> |
  <%= link_to "Back to news", news_index_path %>

  <%= button_to "Destroy this news", @news, method: :delete %>
</div>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/railsblogs/_form.html.erb
<%= form_with(model: railsblog) do |form| %>
  <% if railsblog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(railsblog.errors.count, "error") %> prohibited this railsblog from being saved:</h2>

      <ul>
        <% railsblog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :upload, style: "display: block" %>
    <%= form.text_field :upload %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
 
<% end %>

app/views/railsblogs/_railsblog.html.erb
<div class="container">
<div id="<%= dom_id railsblog %>">



  <p>
    <strong>Title:</strong>
    <%= railsblog.title %>
  </p>

  <p>
    <strong>Upload:</strong>
    <%= railsblog.upload %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= railsblog.description %>
  </p>

</div>
</div>

app/views/railsblogs/edit.html.erb
<h1>Editing railsblog</h1>

<%= render "form", railsblog: @railsblog %>

<br>

<div>
  <%= link_to "Show this railsblog", @railsblog %> |
  <%= link_to "Back to railsblogs", railsblogs_path %>
</div>

app/views/railsblogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Railsblogs</h1>

<div id="railsblogs">
  <% @railsblogs.each do |railsblog| %>
    <%= render railsblog %>
    <p>
      <%= link_to "Show this railsblog", railsblog %>
    </p>
  <% end %>
</div>

<%= link_to "New railsblog", new_railsblog_path %>

app/views/railsblogs/new.html.erb
<h1>Railsblog</h1>

<%= render "form", railsblog: @railsblog %>

<br>

<div>
  <%= link_to "Back to railsblogs", railsblogs_path %>
</div>

app/views/railsblogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @railsblog %>

<div>
  <%= link_to "Edit this railsblog", edit_railsblog_path(@railsblog) %> |
  <%= link_to "Back to railsblogs", railsblogs_path %>

  <%= button_to "Destroy this railsblog", @railsblog, method: :delete %>
</div>